version: '3.7'

services:
    # create a user service from Dockerfile
    users:
        build:
            # where service is located
            context: .
            # where to find Dockerfile for service
            dockerfile: Dockerfile
        entrypoint: ['/usr/src/app/entrypoint.sh']
        # volumes help mount code into container
        # without this, image would need to be rebuilt for every code change
        volumes:
            - .:/user/src/app
        ports:
            - 5001:5000
        environment:
            - FLASK_ENV=development
            - APP_SETTINGS=project.config.DevelopmentConfig
            - DATABASE_URL=postgresql://postgres:postgres@users-db:5432/users_dev
            - DATABASE_TEST_URL=postgresql://postgres:postgres@users-db:5432/users_test
        depends_on: 
            - users-db

    # set up database service
    users-db:
        build:
            # where service is located
            context: ./project/db
            # where to find Dockerfile for service
            dockerfile: Dockerfile
        # this port can be used when other services need this service
        expose:
            - 5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres